window.CollectraPdf = (() => {
  const pageWidth = 595;
  const pageHeight = 842;
  const margin = 54;
  const lineHeight = 18;

  function escapePdf(text) {
    return String(text)
      .replace(/\\/g, "\\\\")
      .replace(/\(/g, "\\(")
      .replace(/\)/g, "\\)");
  }

  function wrapLine(text, maxLength) {
    const words = String(text).split(/\s+/);
    const lines = [];
    let current = "";
    words.forEach((word) => {
      const candidate = current ? `${current} ${word}` : word;
      if (candidate.length > maxLength && current) {
        lines.push(current);
        current = word;
      } else {
        current = candidate;
      }
    });
    if (current) lines.push(current);
    return lines;
  }

  function buildContent(title, sections) {
    const commands = [
      "BT",
      "/F1 24 Tf",
      `${margin} ${pageHeight - 70} Td`,
      `(${escapePdf(title)}) Tj`,
      "/F1 11 Tf",
      `0 -30 Td`,
      `(Generated by Collectra) Tj`,
      `0 -${lineHeight * 2} Td`
    ];

    sections.forEach((section) => {
      commands.push("/F1 15 Tf");
      commands.push(`(${escapePdf(section.heading)}) Tj`);
      commands.push("/F1 11 Tf");
      commands.push(`0 -${lineHeight} Td`);
      section.lines.forEach((line) => {
        wrapLine(line, 82).forEach((wrappedLine) => {
          commands.push(`(${escapePdf(wrappedLine)}) Tj`);
          commands.push(`0 -${lineHeight} Td`);
        });
      });
      commands.push(`0 -${lineHeight} Td`);
    });

    commands.push("ET");
    return commands.join("\n");
  }

  function pdfDocument(title, sections) {
    const content = buildContent(title, sections);
    const objects = [
      "<< /Type /Catalog /Pages 2 0 R >>",
      "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>`,
      "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
      `<< /Length ${content.length} >>\nstream\n${content}\nendstream`
    ];

    let pdf = "%PDF-1.4\n";
    const offsets = [0];
    objects.forEach((object, index) => {
      offsets.push(pdf.length);
      pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
    });

    const xref = pdf.length;
    pdf += `xref\n0 ${objects.length + 1}\n`;
    pdf += "0000000000 65535 f \n";
    offsets.slice(1).forEach((offset) => {
      pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
    });
    pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
    return pdf;
  }

  function download(filename, title, sections) {
    const blob = new Blob([pdfDocument(title, sections)], { type: "application/pdf" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = filename;
    document.body.appendChild(anchor);
    anchor.click();
    anchor.remove();
    window.setTimeout(() => URL.revokeObjectURL(url), 1000);
  }

  return {
    download
  };
})();
